// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StockDataLib.Data;

#nullable disable

namespace StockDataLib.Migrations
{
    [DbContext(typeof(StockDataContext))]
    [Migration("20251026170329_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StockDataLib.Models.BorrowFeeData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AvailableShares")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Fee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockTickerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StockTickerId", "Date")
                        .IsUnique();

                    b.ToTable("BorrowFeeData");
                });

            modelBuilder.Entity("StockDataLib.Models.PriceData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Close")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("High")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Low")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Open")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockTickerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StockTickerId", "Date")
                        .IsUnique();

                    b.ToTable("PriceData");
                });

            modelBuilder.Entity("StockDataLib.Models.RedditMentionData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Mentions")
                        .HasColumnType("int");

                    b.Property<string>("Sentiment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StockTickerId")
                        .HasColumnType("int");

                    b.Property<string>("TopSubreddit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StockTickerId", "Date")
                        .IsUnique();

                    b.ToTable("RedditMentionData");
                });

            modelBuilder.Entity("StockDataLib.Models.ShortInterestData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<long>("SharesShort")
                        .HasColumnType("bigint");

                    b.Property<decimal>("ShortInterest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockTickerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StockTickerId", "Date")
                        .IsUnique();

                    b.ToTable("ShortInterestData");
                });

            modelBuilder.Entity("StockDataLib.Models.ShortPositionData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<long>("PositionChange")
                        .HasColumnType("bigint");

                    b.Property<int>("StockTickerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StockTickerId", "Date")
                        .IsUnique();

                    b.ToTable("ShortPositionData");
                });

            modelBuilder.Entity("StockDataLib.Models.ShortVolumeData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<long>("ShortVolume")
                        .HasColumnType("bigint");

                    b.Property<decimal>("ShortVolumePercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockTickerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StockTickerId", "Date")
                        .IsUnique();

                    b.ToTable("ShortVolumeData");
                });

            modelBuilder.Entity("StockDataLib.Models.StockTicker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.ToTable("StockTickers");
                });

            modelBuilder.Entity("StockDataLib.Models.VolumeData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("StockTickerId")
                        .HasColumnType("int");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("StockTickerId", "Date")
                        .IsUnique();

                    b.ToTable("VolumeData");
                });

            modelBuilder.Entity("StockDataLib.Models.BorrowFeeData", b =>
                {
                    b.HasOne("StockDataLib.Models.StockTicker", "StockTicker")
                        .WithMany("BorrowFeeData")
                        .HasForeignKey("StockTickerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StockTicker");
                });

            modelBuilder.Entity("StockDataLib.Models.PriceData", b =>
                {
                    b.HasOne("StockDataLib.Models.StockTicker", "StockTicker")
                        .WithMany("PriceData")
                        .HasForeignKey("StockTickerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StockTicker");
                });

            modelBuilder.Entity("StockDataLib.Models.RedditMentionData", b =>
                {
                    b.HasOne("StockDataLib.Models.StockTicker", "StockTicker")
                        .WithMany("RedditMentionData")
                        .HasForeignKey("StockTickerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StockTicker");
                });

            modelBuilder.Entity("StockDataLib.Models.ShortInterestData", b =>
                {
                    b.HasOne("StockDataLib.Models.StockTicker", "StockTicker")
                        .WithMany("ShortInterestData")
                        .HasForeignKey("StockTickerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StockTicker");
                });

            modelBuilder.Entity("StockDataLib.Models.ShortPositionData", b =>
                {
                    b.HasOne("StockDataLib.Models.StockTicker", "StockTicker")
                        .WithMany("ShortPositionData")
                        .HasForeignKey("StockTickerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StockTicker");
                });

            modelBuilder.Entity("StockDataLib.Models.ShortVolumeData", b =>
                {
                    b.HasOne("StockDataLib.Models.StockTicker", "StockTicker")
                        .WithMany("ShortVolumeData")
                        .HasForeignKey("StockTickerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StockTicker");
                });

            modelBuilder.Entity("StockDataLib.Models.VolumeData", b =>
                {
                    b.HasOne("StockDataLib.Models.StockTicker", "StockTicker")
                        .WithMany("VolumeData")
                        .HasForeignKey("StockTickerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StockTicker");
                });

            modelBuilder.Entity("StockDataLib.Models.StockTicker", b =>
                {
                    b.Navigation("BorrowFeeData");

                    b.Navigation("PriceData");

                    b.Navigation("RedditMentionData");

                    b.Navigation("ShortInterestData");

                    b.Navigation("ShortPositionData");

                    b.Navigation("ShortVolumeData");

                    b.Navigation("VolumeData");
                });
#pragma warning restore 612, 618
        }
    }
}
