version: '3.8'

services:
  # SQL Server
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-CU12-ubuntu-22.04
    environment:
      SA_PASSWORD: "StrongPassword123!"
      ACCEPT_EULA: "Y"
    user: root
    ports:
      - "1433:1433"
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "$$SA_PASSWORD" -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
    volumes:
      - mssql_data:/var/opt/mssql/data

  # API
  api:
    build:
      context: .
      dockerfile: src/StockDataApi/Dockerfile
      cache_from:
        - mcr.microsoft.com/dotnet/sdk:9.0
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - AlphaVantage__ApiKey=demo
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - stock-data-network

  # Worker
  worker:
    build:
      context: .
      dockerfile: src/StockDataWorker/Dockerfile
      cache_from:
        - mcr.microsoft.com/dotnet/sdk:9.0
    environment:
      - DOTNET_ENVIRONMENT=Development
      - AlphaVantage__ApiKey=demo
    depends_on:
      sqlserver:
        condition: service_healthy
      api:
        condition: service_started
    networks:
      - stock-data-network

networks:
  stock-data-network:
    driver: bridge

volumes:
  mssql_data:

# Made with Bob
